[package]
name = "memhook"
version = "0.1.0"
edition = "2021"

[dependencies]
fishhook = { path = "../.." }
libc = "0.2"
ctor = "0.2.8"
backtrace = "0.3"
addr2line = "0.24"
inferno = "0.12.0"

[profile.release]
debug = true

[lib]
crate-type = ["dylib"]